### ISSUE TITLE
PLEASE GOD ADD THIS:

### ISSUE THREAD

**Issue by RyanThompson** [bloveless/creative-theme#1]
`{% for style in asset_styles("styles.css") %}
    {{ style|raw }}
{% endfor %}`

In the meta data under style.css .. I keep forgetting to add it every time I pull and wonder why blocks / partials start to misbehave lol

^_^

**Comment by bloveless** [comment]
Added! Not sure if it matters where I added it. Pull!

**Comment by bloveless** [comment]
Is there a way to get these css files combined with the style.css file that already exists in there?

**Comment by RyanThompson** [comment]
No because the style.css is the static / theme styles combined into one. Styles.css holds files that come and go depending on the page / load / ever'thing.

**Comment by RyanThompson** [comment]
Might be able to cache it smarter in der future but.. Pry not priority now :-(
